# Generated by Django 3.1.1 on 2020-10-01 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_auto_20201001_1614'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskhistory',
            name='date',
            field=models.DateTimeField(null=True),
        ),
    ]
