# Generated by Django 3.1.1 on 2020-10-01 13:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_taskhistory_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskhistory',
            name='task_id',
        ),
        migrations.AddField(
            model_name='taskhistory',
            name='task',
            field=models.IntegerField(),
            preserve_default=False,
        ),
    ]
