# Generated by Django 3.1.1 on 2020-10-01 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0009_auto_20201001_1645'),
    ]

    operations = [
        migrations.RenameField(
            model_name='taskhistory',
            old_name='task',
            new_name='task_id',
        ),
        migrations.RemoveField(
            model_name='taskhistory',
            name='date',
        ),
    ]
